---
title: "Democratic Backsliding"
author: "Noah Dasanaike"
date: "11/1/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(readxl)
library(stats)
library(janitor)
library(rstanarm)
library(rsample)

# Maps

library(rdrop2)
library(leaflet)
library(rgdal)
library(countrycode)

demean.mat <- function(xmat) {
  apply(xmat, 2, function(z) z - mean(z))
}
```

```{r one}
eui <- read_xlsx("data/EIU.xlsx", sheet = "MERGEPublic") %>%
  rename(country = ...1)

variables <- substr(colnames(eui)[3:8], start = 6, stop = 7)
years <- as.character(1996:2019)

eui_fixed <- tibble(country = 0, year = 0)
for(i in 1:length(variables)){
  eui_fixed[, ncol(eui_fixed) + 1] <- rnorm(nrow(eui_fixed))
  names(eui_fixed)[ncol(eui_fixed)] <- paste0(variables[i])
}


country_index = 2
inner_index = 0
insert_vector <- NULL

for (y in 2:nrow(eui)){
  insert_vector["country"] = eui[[1]][y]
  for (i in 3:length(colnames(eui))){
    if (inner_index == 6){
      eui_fixed <- rbind(eui_fixed, insert_vector)
      insert_vector <- NULL
      insert_vector["country"] = eui[[1]][y]
      inner_index = 0
    }
    
    insert_vector["year"] = eui[1, i]
      
    for (p in 1:length(variables)){
      if (grepl(variables[p], colnames(eui)[i])){
        insert_vector[variables[p]] = eui[y, i]
        inner_index = inner_index + 1
      }
    }
  }
}

eui_subset <- eui_fixed %>% 
  slice(-1) %>%
  drop_na() %>%
  clean_names() %>%
  mutate(va = as.numeric(va),
         pv = as.numeric(pv),
         ge = as.numeric(ge),
         rq = as.numeric(rq),
         rl = as.numeric(rl),
         cc = as.numeric(cc))

eui_subset <- eui_subset[complete.cases(eui_subset), ]

eui_matrix <- eui_subset %>%
  select(-c(country, year)) %>%
  as.matrix() %>%
  demean.mat()

udv <- svd(eui_matrix)
v1 <- matrix(udv$v[,1], ncol = 1); e1 <- eui_matrix%*%v1 * -1

eui_subset$index <- e1
```

```{r graph}
eui_map <- eui_subset %>%
  rowwise() %>%
  mutate(country_code = 
           countrycode(country, origin = "country.name", destination = "iso3c"))

min = min(eui_map$index)
max = max(eui_map$index)

eui_map <- eui_map %>%
  rowwise() %>%
  mutate(standard = (index-min)/(max-min))

eui_subset %>%
  filter(country %in% c("France", "United Kingdom", "Germany")) %>%
  ggplot(aes(x = year, y = index, group = country, year = country)) +
  geom_line()
```

```{r comparison}
diff <- eui_subset %>%
  filter(year %in% c("2019", "2017"))

# year one is later year
# year two is earlier year

min = min(diff$index)
max = max(diff$index)

diff_one <- diff %>%
  filter(year %in% c("2019")) %>%
  rowwise() %>%
  mutate(standard = (index - min) / (max - min)) %>%
  bootstraps(times = 1000) %>%
  mutate(boot = map(splits, ~ analysis(.))) %>%
  mutate(index = map(boot, ~ pull(., index))) %>% 
  mutate(index_mean = map_dbl(index, ~ mean(.)))

year_one <- stan_glm(data = diff_one, 
                    index_mean ~ 1, 
                    family = gaussian(), 
                    refresh = 0)

diff_two <- diff %>%
  filter(year %in% c("2017")) %>%
  rowwise() %>%
  mutate(standard = (index - min) / (max - min)) %>%
  bootstraps(times = 1000) %>%
  mutate(boot = map(splits, ~ analysis(.))) %>%
  mutate(index = map(boot, ~ pull(., index))) %>% 
  mutate(index_mean = map_dbl(index, ~ mean(.)))

year_two <- stan_glm(data = diff_two, 
                    index_mean ~ 1, 
                    family = gaussian(), 
                    refresh = 0)

year_one <- year_one %>%
  as_tibble() %>%
  select(-sigma) %>%
  rename(index = `(Intercept)`)

year_two <- year_two %>%
  as_tibble() %>%
  select(-sigma) %>%
  rename(index = `(Intercept)`)

cols <- c("bar_1"="#f54242", "bar_2" = "#b8b2ad")

ggplot() +
  geom_histogram(data = year_one, aes(x = index, y = after_stat(count/sum(count)),
                                      fill = "bar_1"), 
                 color = "black", alpha = 0.8) +
  geom_histogram(data = year_two, aes(x = index, y = after_stat(count/sum(count)),
                                      fill = "bar_2"), 
                 color = "black", alpha = 0.8) +
  labs(title = "Likely Mean Democratic Index",
         x = "Mean Index",
         y = "Probability") +
  theme_bw() + 
  scale_fill_manual(name = "Bar", values = cols, labels = c("2019", "2017"))
```


```{r map}
world_spdf <- readOGR( 
            dsn = paste0("map_files/"), 
            layer = "TM_WORLD_BORDERS_SIMPL-0.3",
            verbose = FALSE)
        
        world_spdf@data <- world_spdf@data %>%
            rename(country_code = "ISO3") %>%
            merge(eui_map[which(eui_map$year == "2019"),], 
                  by = "country_code", keep.x = TRUE)
        
        color_pal <- colorQuantile("Reds", world_spdf@data$standard, n = 7)
        
        leaflet(world_spdf) %>% 
            addTiles()  %>% 
            setView(lat = 10, lng = 0, zoom = 2) %>%
            addPolygons( 
                color = ~color_pal(standard),
                stroke = TRUE, 
                fillOpacity = 0.9, 
                weight = 0.3,
                )
```